# Development overrides
version: '3.8'

services:
  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    
  backend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/backend:/app:cached
      - backend_node_modules:/app/node_modules
      - backend_dist:/app/dist