# Development overrides
services:
  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    
  backend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
      - backend_dist:/app/dist